run: don't use [] in call to venv, don't run cmd if one fails

diff --git a/software/script/run b/software/script/run
--- a/software/script/run
+++ b/software/script/run
@@ -4,12 +4,10 @@ name=$(basename "$0")
 
 if ! [ -f "bin/activate" ]; then
   printf "$name: rtfm\n"
-  if ! [ ./script/venv ]; then
-    printf "$name: installation of venv failed"
+  if !  ./script/venv; then
+    printf "$name: installation of venv failed\n"
     exit 1
   fi
 fi
 
-source bin/activate
-python3.10 main.py
-deactivate
+source bin/activate && python3.10 main.py && deactivate
